version: '3.9'
services:
  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    container_name: gateway-service
    env_file:
      - .env
    environment:
      - USER_SERVICE_URL=${USER_SERVICE_URL}
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - user-service

  user-service:
    build:
      context: .
      dockerfile: service/Dockerfile
    container_name: user-service
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: login-frontend
    depends_on:
      - gateway
    environment:
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_GATEWAY_URL}
    ports:
      - "3000:3000"
    restart: unless-stopped
